### ISSUE TITLE
I can't get this to work.

### ISSUE THREAD

**Issue by johnfn** [vshaxe/vscode-terminator#1]
I followed the directions exactly, but got: "Running the contributed command:'terminator.run' failed".

**Comment by Gama11** [comment]
Usually, there's some output / a stacktrace in the dev console with an error like that, anything interesting there?

What does your keybinding look like and what's the task you're trying to run?

**Comment by Gama11** [comment]
I'm going to need more info to be able to help you with this. Closing for now since there hasn't been any followup.
