### ISSUE TITLE
Getting error when building more than once: Terminal with ID 1 does not exist (has it already been disposed?)

### ISSUE THREAD

**Issue by TaylorAnderson** [vshaxe/vscode-terminator#2]
The title is fairly self-explanatory.  I have to then retry the build to get it to actually work.  Every time it happens that number increments (so second try would be "Terminal with ID 2...")

**Comment by Gama11** [comment]
Yes, I've gotten reports of this from several people, and reported an issue on the VSCode repo here: https://github.com/Microsoft/vscode/issues/53331

**Comment by Gama11** [comment]
This should be fixed now: https://github.com/Microsoft/vscode/issues/60858
